import type { NextPage } from 'next';
import Head from 'next/head';
import TailwindCssNotification from '../components/utility-first/tailwind-css-notification';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TailwindCssNotification />
    </>
  );
};

export default Home;
