import type { NextPage } from 'next';
import Head from 'next/head';
import BreakpointResponsiveCard from '../components/responsive-design/media-responsive-card';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BreakpointResponsiveCard />
    </>
  );
};

export default Home;
